# Generated by Django 3.0.2 on 2020-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
