# Generated by Django 3.0.2 on 2020-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200719_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('all', 'ALL'), ('school_books', 'Scchool Books'), ('college_books', 'College Books'), ('biographic', 'Biographic'), ('adventure', 'Adventure'), ('childern', 'Childern'), ('cook', 'Cook'), ('treding', 'Trending'), ('other', 'Other')], default='Other', max_length=50),
        ),
    ]
