# Generated by Django 3.0.2 on 2020-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books_college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('cource', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='books_eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('year', models.CharField(default='1', max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='books_medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('year', models.CharField(default='1', max_length=50)),
                ('field', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='books_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
