# Generated by Django 3.0.2 on 2020-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_college',
            name='img_1side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_college',
            name='img_2side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_college',
            name='index_1',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_college',
            name='index_2',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_college',
            name='index_3',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_college',
            name='index_4',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='img_1side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='img_2side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='index_1',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='index_2',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='index_3',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_eng',
            name='index_4',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='img_1side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='img_2side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='index_1',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='index_2',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='index_3',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_medical',
            name='index_4',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='img_1side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='img_2side',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='index_1',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='index_2',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='index_3',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='books_school',
            name='index_4',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
    ]
