# Generated by Django 3.0.2 on 2020-06-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0002_auto_20200621_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_medical',
            old_name='img_1side',
            new_name='book_index_1',
        ),
        migrations.RenameField(
            model_name='books_medical',
            old_name='img_2side',
            new_name='book_index_2',
        ),
        migrations.RenameField(
            model_name='books_medical',
            old_name='index_1',
            new_name='book_index_3',
        ),
        migrations.RenameField(
            model_name='books_medical',
            old_name='index_2',
            new_name='book_index_4',
        ),
        migrations.RenameField(
            model_name='books_medical',
            old_name='index_3',
            new_name='bookback_cover',
        ),
        migrations.RenameField(
            model_name='books_medical',
            old_name='index_4',
            new_name='bookfront_cover',
        ),
    ]
