# Generated by Django 3.0.2 on 2020-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0003_auto_20200626_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books_school',
            old_name='img_1side',
            new_name='bookback_cover',
        ),
        migrations.RenameField(
            model_name='books_school',
            old_name='img_2side',
            new_name='bookfront_cover',
        ),
    ]
