# Generated by Django 3.0.2 on 2020-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0004_auto_20200629_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('bookfront_cover', models.ImageField(default='picc', upload_to='pics')),
            ],
        ),
    ]
