# Generated by Django 3.0.2 on 2020-07-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
