# Generated by Django 3.0.2 on 2020-07-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_books', '0012_auto_20200708_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
