# Generated by Django 3.0.2 on 2020-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bestseller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='hot',
            field=models.BooleanField(default=True),
        ),
    ]
