# Generated by Django 3.0.2 on 2020-06-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='book_down',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='book_up',
        ),
        migrations.AddField(
            model_name='cart',
            name='book_index_1',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='cart',
            name='book_index_2',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='cart',
            name='book_index_3',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='cart',
            name='book_index_4',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='cart',
            name='bookback_cover',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='cart',
            name='bookfront_cover',
            field=models.ImageField(default='picc', upload_to='pics'),
        ),
    ]
