# Generated by Django 3.0.2 on 2020-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200626_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
